[project]
name = "ds-utils"
version = "0.1.0"
description = "Utilities for data science, EDA, data preprocessing and machine learning"
readme = "README.md"
authors = [
    { name = "Juanjo Garcia", email = "juanjosgg@gmail.com" }
]
requires-python = ">=3.12, <4.0"
license = { file = "LICENSE" }


dependencies = [
    "numpy>=2.0",
    "pandas>=2.2",
]


[project.optional-dependencies]
eda = [
    "ipython>=8.0",
    "matplotlib>=3.9"
]

ml = [
    "scikit-learn>=1.5",
]


[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.12",
    "mypy>=1.0",
]

